- name: Add Varnish Plus repo
  block:
    - set_fact:
        varnish_repo_key_url: https://{{ settings['varnish-plus'].user }}:@packagecloud.io/varnishplus/{{ settings['varnish-plus'].version }}/gpgkey

    - name: Add Varnish Plus repo key
      shell: |
        set -e
        curl -L {{ varnish_repo_key_url }} | apt-key add -
        touch /home/vagrant/.vagrant.varnish.add-varnish-plus-repo-key
      args:
        creates: /home/vagrant/.vagrant.varnish.add-varnish-plus-repo-key

    - name: Add Varnish Plus repo
      apt_repository:
        filename: varnish-plus
        repo: deb https://{{ settings['varnish-plus'].user }}:@packagecloud.io/varnishplus/{{ settings['varnish-plus'].version }}/ubuntu/ xenial main
        update_cache: True

- name: Install Varnish Plus packages
  apt:
    name:
      - varnish-plus
    update_cache: True

- name: Enable & start VCP service
  service:
    name: varnish
    enabled: yes
    state: started
